server:
  port: 9001
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-user
  registry:
    address: zookeeper://192.168.92.133:2181?backup=192.168.92.133:2182,192.168.92.133:2183